export const products = [
      {
            id: 1,
            name: "Ada Sofa",
            title: "Ada's Sweet Dreams",
            price: 59000,
            rating: 3,
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            category: "sofa",
            colors: ["blue", "gray", "white"],
            img: "ada-sofa",
            discount: 10,
            featured: ["newly available", " #1e6cc4"],
      },
      {
            id: 2,
            name: "Bisoye Sofa",
            title: "Swedish Confy Paradise",
            price: 118000,
            rating: 3,
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            category: "sofa",
            colors: ["gray", "blue", "white", "grey", "gold"],
            img: "bisoye-sofa",
            discount: 15,
            featured: ["popular", "#c8c8c7"],
      },
      {
            id: 3,
            name: "Shobo Chair",
            title: " Framer Paddle Shobo Chair",
            img: "shobo-chair",
            price: 32000,
            rating: 4,
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            category: "chair",
            colors: ["gold", "blue", "gray", "black"],
            discount: 5,
            featured: ["Most liked", "#d9e26c"],
      },
      {
            id: 4,
            name: "Lamp Connector",
            title: "Extension for Long Connection ",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "lamp-connector",
            rating: 4.2,
            category: "lamp",
            price: 10000,
            colors: ["black", "white"],
            discount: 25,
            featured: ["hot deals"],
      },
      {
            id: 5,
            name: "Dinma Duo Sofa",
            title: "Odikanma Braging Piece",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "dinma-duo-sofa",
            rating: 3.5,
            category: "sofa",
            price: 450000,
            colors: ["black", "blue", "grey", "yellow"],
            discount: 7,
      },
      {
            id: 6,
            name: "Hamida Sofa",
            title: "Hamida Living Legacy",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "hamida-sofa",
            rating: 3.5,
            category: "sofa",
            price: 450000,
            colors: ["gray", "grey"],
            discount: 5,
      },
      {
            id: 7,
            name: "Ikenga Chair",
            title: "Work Life in Ikenga",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "ikenga-chair",
            rating: 4,
            category: "chair",
            price: 25000,
            colors: ["black", "blue", "yellow"],
            discount: 9,
      },
      {
            id: 8,
            name: "Labi Tv Console",
            title: "Right Corner Piece",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "labi-tv-console",
            rating: 4.5,
            category: "console",
            price: 35000,
            discount: 18,
      },
      {
            id: 9,
            name: "Wall Clock",
            title: "Swedish Ticking Piece",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "wall-clock",
            rating: 5,
            category: "clock",
            price: 20000,
            discount: 0,
      },
      {
            id: 10,
            name: "Seje L-Shaped Sofa",
            title: "Baron de Seje",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "seje-l-shaped-sofa",
            rating: 4.9,
            category: "sofa",
            price: 450000,
            colors: ["black", "blue", "grey", "yellow"],
            discount: 0,
      },
      {
            id: 11,
            name: "Timini Pillow",
            title: "Foamy Sleepy Paradise",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "timini-pillow",
            rating: 4.0,
            category: "bed",
            price: 400000,
            discount: 15,
      },
      {
            id: 12,
            name: "Alausa Sofa",
            title: "Eko Love birds",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "alausa-sofa",
            rating: 4.9,
            category: "sofa",
            price: 70000,
            colors: ["white", "grey", "yellow"],
            discount: 5,
      },
      {
            id: 13,
            name: "Amakisi Table",
            title: "Reading Corner Table",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "amakisi-table",
            rating: 3.8,
            category: "table",
            price: 21000,
            colors: ["black", "white"],
            discount: 0,
      },
      {
            id: 14,
            name: "Anuli Cloth Rack",
            title: "Dry Space Anuli Hanger",
            description:
                  " Made from the finest silk material, with the best italian woods, this armless chair gives you the confidence, unique style and comfort with elegance.",
            img: "anuli-cloth-rack-hanger",
            rating: 4.2,
            category: "hanger",
            price: 28000,
            colors: ["black", "white"],
            discount: 10,
      },
];
